### ISSUE TITLE
Check out nlmixr and propose an API for tdmore

### ISSUE THREAD

**Issue by rfaelens** [tdmore-dev/tdmore#13]
Read the documentation for the nlmixr DSL https://nlmixrdevelopment.github.io/nlmixr_bookdown/vignettes.html#nlmixr-domain-specific-language

And use this to propose an API for tdmore. I would suggest to simply recycle an nlmixr object, as follows:

```{r}
my2CptModel <- function() {
  ini({
    tka <- log(1.14)
    tcl <- log(0.0190)
    tv2  <- log(2.12)
    tv3  <- log(20.4)
    tq   <- log(0.383)
    wteff  <- 0.35
    sexeff <- -0.2
    eta.ka ~ 1
    eta.cl ~ 1
    eta.v2 ~ 1
    eta.v3 ~ 1
    eta.q ~ 1
    prop.err <- 0.075
  })
  model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + wteff*lWT + eta.cl)
    v2 <- exp(tv2 + sexeff*SEX + eta.v2)
    v3 <- exp(tv3 + eta.v3)
    q  <- exp(tq + eta.q)
    d/dt(depot) = -ka * depot
    d/dt(center) = ka * depot - cl / v2 * center + q/v3 * periph - q/v2 * center
    d/dt(periph) = q/v2 * center - q/v3 * periph
    cp = center / v2
    cp ~ prop(prop.err)
  })
}

my2CptFit <- my2CptModel %>% nlmixr() %>% tdmore()
```

As a reference, the current API for use with RxODE objects is as follows:
![image](https://user-images.githubusercontent.com/1379970/45764445-018a6080-bc33-11e8-83bf-884acacb5533.png)

**Comment by luyckxn** [comment]
There is a nice function in nlmixr called 'nlmixrUI'  that converts the model (string form) into a nlmixrUI object. Most information from the model can be found in a straightforward way. E.g.: all thetas/omegas  estimates (lower, upper, initial estimate, name, position in equation, etc), the error model (add, prop), all the covariates, all the variable names etc... Probably a good object to reuse.

Regarding mu-referencing in nlmixr, log( WT/70 ) is allowed in the model, depending on the estimation method used... For saem, mu-referencing is required, for nlme it is not.

**Comment by luyckxn** [comment]
What do you mean exactly by: 'Can we immediately calculate the residuals?'. I'm not sure to understand.

**Comment by rfaelens** [comment]
We have to calculate two different "log-likelihoods".

The log-likelihood of individual eta's can be calculated by using the OMEGA
matrix. We know (by definition) that ETA is normally distributed.

However, for the residual error (model prediction vs actual concentration),
there are several residual error models possible. In NONMEM, you can define
the log-likelihood function yourself (e.g. when estimating a
poisson-distributed value, or when applying the M3 method). In nlmixr, it
seems you define the residual error by using some type of macro?
It would be nice if we can define a function residuals.nlmixrUI(x,
observed, predicted) that automatically asks for the residual
log-likelihood.

/ Ruben

Op vr 28 sep. 2018 om 18:46 schreef luyckxn <notifications@github.com>:
