### ISSUE TITLE
Use optim() framework for optimization method

### ISSUE THREAD

**Issue by rfaelens** [tdmore-dev/tdmore#26]
The `optim()` method should be used when performing optimization (e.g. in the `estimate` method).

We should be using sensible defaults (i.e. "method=L-BFGS-B", with `maxstep = diag(sqrt(omega))` ), but allow overriding these options in the arguments of `estimate`.

**Comment by nluyckx** [comment]
To be reviewed tomorrow but I think this issue can be closed.

**Comment by rfaelens** [comment]
Great
