### ISSUE TITLE
nlmixr2 compatibility

### ISSUE THREAD

**Issue by WhitishPoison** [tdmore-dev/tdmore#72]
Hi, I wonder if there is a way fit nlmixr2 output. I get the error message that the model is not compatible with TDM. While nlmixr outfit is compatible, for model fitting purposes it is better for me to use nlmixr2.

**Comment by rfaelens** [comment]
Feel free to propose a Pull Request, I will happily accept this functionality!
The namespaces should be clean enough that RxOde2 can be added as an extra simulation engine, and to add import of nlmixr2 models.
This project is not a priority for me anymore, so I may only get around to this in a few months.
